/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cliente;
import Clases.Detalle_venta;
import Clases.Producto;
import Clases.Venta;
import Dao.Dao_Detalle_venta;
import Dao.Dao_Producto;
import Dao.Dao_Venta;
import Estructuras.ArbolBBDetalleVenta;
import Estructuras.ListaDobleDetalleVenta;
import Meet.Alertas;
import Modelos.Modelo_DetalleVenta;
import MyOption.Confirmar;
import MyOption.JOptionPaneError;
import MyOption.JOptionPaneInfo;
import MyOption.JOptionPaneWornin;
import java.util.ArrayList;

/**
 *
 * @author leo_g
 */
public class AddDetalleVenta1 extends javax.swing.JDialog {

    int x = 0, y = 0, filaseleccionada = 0;
    ListaDobleDetalleVenta lista;
    Detalle_venta venta;
    Modelo_DetalleVenta ml;
    Alertas aler;
    Dao_Detalle_venta ven;
    ArrayList<Venta> combove;
    ArrayList<Producto> combo;
    ArrayList<String> clie;
    ArrayList<String> combovv;
    ArrayList<Detalle_venta> refere;
    ArrayList<Detalle_venta> refere2;
    ArbolBBDetalleVenta albolbusquedad;
    Dao_Producto pro;
    String clien;
    String clienven;
    String tipo1;
    double totalfac = 0;
    int cont = 0;

    /**
     * Creates new form AddDetalleVenta
     */
    public AddDetalleVenta1(java.awt.Frame parent, boolean modal, ArrayList<Producto> combo1, ArrayList<Venta> combo2, ArrayList<Detalle_venta> referen, String clien1, String clienven1, String tipo2, int ccc1) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        aler = new Alertas();
        lista = new ListaDobleDetalleVenta();
        venta = new Detalle_venta();
        ven = new Dao_Detalle_venta();
        clie = new ArrayList();
        refere = new ArrayList();
        combovv = new ArrayList();
        albolbusquedad = new ArbolBBDetalleVenta();
        pro = new Dao_Producto();
        refere2 = referen;
        combo = combo1;
        combove = combo2;
        clien = clien1;
        clienven = clienven1;
        tipo1 = tipo2;
        if (combove != null) {
            for (Venta e : combove) {
                ventadd.setText(e.getNumerofactura());
            }
        }

        if (!clienven.equals("")) {
            ventadd.setText(clienven);
            llenarTabla();
        }
        if (ccc1 != 0) {
            cont = ccc1;
        }
         llenarTabla();
    }
    public void llenarLista() {
        lista = new ListaDobleDetalleVenta();
        for (Detalle_venta w : ven.listaDetalle_venta()) {
            if (ventadd.getText().isEmpty()) {
                venta = new Detalle_venta(w.getId_detalle(), new Producto(w.getId_producto().getNombre()), w.getCantidad(), new Venta(w.getId_datos_venta().getNumerofactura()), new Cliente(w.getCliente().getNombre()), w.getTipo());
                lista.insertar(venta);
            } else {
                if (w.getId_datos_venta().getNumerofactura().equals(ventadd.getText())) {
                    venta = new Detalle_venta(w.getId_detalle(), new Producto(w.getId_producto().getNombre()), w.getCantidad(), new Venta(w.getId_datos_venta().getNumerofactura()), new Cliente(w.getCliente().getNombre()), w.getTipo());
                    lista.insertar(venta);
                }
            }
        }
    }

    public void llenarArbol() {
        albolbusquedad = new ArbolBBDetalleVenta();
        for (Detalle_venta w : ven.listaDetalle_venta()) {
            venta = new Detalle_venta(w.getId_detalle(), new Producto(w.getId_producto().getNombre()), w.getCantidad(), new Venta(w.getId_datos_venta().getNumerofactura()), new Cliente(w.getCliente().getNombre()), w.getTipo());
            albolbusquedad.insertar(venta);
        }
    }

    public void llenarTabla() {
        llenarLista();
        Modelo_DetalleVenta ml = new Modelo_DetalleVenta(lista.toArrayAsc());
        tabla.setModel(ml);
    }

    public void llenarcombo() {
        combovv.clear();
        llenarLista();
        for (Object e : lista.toArrayAsc()) {
             System.out.println(String.valueOf(((Detalle_venta) e).getId_detalle()));
            combovv.add(String.valueOf(((Detalle_venta) e).getId_detalle()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        datocredito = new javax.swing.JMenuItem();
        jRadioButton1 = new javax.swing.JRadioButton();
        encabezado = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ventadd = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        barraBaja = new javax.swing.JPanel();
        salir = new javax.swing.JPanel();
        volver = new javax.swing.JLabel();
        buscarn = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        datocredito.setText("Agregar Datos de  Credito");
        datocredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datocreditoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(datocredito);

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        encabezado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encabezado.setText("Nueva Venta");
        encabezado.setToolTipText("");
        encabezado.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        encabezado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                encabezadoMouseDragged(evt);
            }
        });
        encabezado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                encabezadoMousePressed(evt);
            }
        });
        getContentPane().add(encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 760, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Venta");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 150, -1));

        ventadd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ventadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 138, 32), 1, true));
        ventadd.setEnabled(false);
        getContentPane().add(ventadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 280, 24));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bolsa-de-la-compra.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setComponentPopupMenu(jPopupMenu1);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 740, -1));

        barraBaja.setBackground(new java.awt.Color(236, 138, 32));

        salir.setBackground(new java.awt.Color(238, 238, 238));
        salir.setForeground(new java.awt.Color(238, 238, 238));

        volver.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(236, 138, 32));
        volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver.setText("Volver");
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout salirLayout = new javax.swing.GroupLayout(salir);
        salir.setLayout(salirLayout);
        salirLayout.setHorizontalGroup(
            salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        salirLayout.setVerticalGroup(
            salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        buscarn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarnKeyReleased(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraBajaLayout = new javax.swing.GroupLayout(barraBaja);
        barraBaja.setLayout(barraBajaLayout);
        barraBajaLayout.setHorizontalGroup(
            barraBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraBajaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(buscarn, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        barraBajaLayout.setVerticalGroup(
            barraBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraBajaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(barraBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(barraBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3))
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(barraBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 760, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-window-20 (1).png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-window-20.png"))); // NOI18N
        jButton7.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-window-20.png"))); // NOI18N
        jButton7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-window-20.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 210, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encabezadoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encabezadoMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_encabezadoMouseDragged

    private void encabezadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encabezadoMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_encabezadoMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        if (saveE.getText().equals("Editar")) {
//            refere.add(new Detalle_venta(new Producto(producto.getText()), Integer.parseInt(String.valueOf(cantidad.getValue())), new Venta(ventadd.getText())));
//            viewVenta cli = new viewVenta(null, true, refere, "", tipo1);
//            this.dispose();
//            cli.setVisible(true);
//        } else {
//            if (producto.getText().isEmpty()) {
//                JOptionPaneWornin a = new JOptionPaneWornin(null, true, "Registro", "LLenar Campo Cliente..");
//                a.setVisible(true);
//            } else {
            viewVenta1 cli = new viewVenta1(null, true,null,tipo1);
            this.dispose();
            cli.setVisible(true);
//            }
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        filaseleccionada = tabla.getSelectedRow();
        if (filaseleccionada >= 0) {
            if (String.valueOf(tabla.getValueAt(filaseleccionada, 4)).equals("Normal")) {
                datocredito.setEnabled(false);
            } else {
                datocredito.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
//        AddVenta a = new AddVenta(null, true, null, null, null, "", tipo1);
        this.dispose();
//        a.setVisible(true);
    }//GEN-LAST:event_volverMouseClicked

    private void buscarnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarnKeyReleased
        // TODO add your handling code here:
        if (buscarn.getText().isEmpty()) {
            llenarTabla();
        }
        ArrayList<Detalle_venta> nuevali = new ArrayList<Detalle_venta>();
        nuevali = buscar(buscarn.getText(), lista.toArrayAsc());
        lista = new ListaDobleDetalleVenta();
        for (Detalle_venta w : nuevali) {
            venta = new Detalle_venta(w.getId_detalle(), new Producto(w.getId_producto().getNombre()), w.getCantidad(), new Venta(w.getId_datos_venta().getNumerofactura()), new Cliente(w.getCliente().getNombre()), w.getTipo());
            lista.insertar(venta);
        }
        Modelo_DetalleVenta ml = new Modelo_DetalleVenta(lista.toArrayAsc());
        tabla.setModel(ml);
    }//GEN-LAST:event_buscarnKeyReleased
    public ArrayList<Detalle_venta> buscar(String nom, ArrayList<Detalle_venta> lis) {
        ArrayList<Detalle_venta> nuevalis = new ArrayList<Detalle_venta>();
        for (Detalle_venta pd : lis) {
            int resultado = pd.getId_producto().getNombre().indexOf(nom);
            if (resultado != -1) {
                nuevalis.add(pd);
            }
        }
        return nuevalis;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if (buscarn.getText().isEmpty()) {
                JOptionPaneWornin a = new JOptionPaneWornin(null, true, "Registro", "LLenar Campos");
                a.setVisible(true);
                buscarn.requestFocus();
            } else {
                llenarArbol();
                String nom = ((Detalle_venta) albolbusquedad.buscar(buscarn.getText()).getDato()).getId_producto().getNombre();
                if (nom.equals("")) {
                    JOptionPaneInfo a = new JOptionPaneInfo(null, true, "Busqueda", "No se pudo encontarar el registro solo 'Similares'!!!...");
                    a.setVisible(true);
                } else {
                    lista = new ListaDobleDetalleVenta();
                    for (Detalle_venta w : ven.listaDetalle_venta()) {
                        if (w.getId_producto().getNombre().equals(nom)) {
                            venta = new Detalle_venta(w.getId_detalle(), new Producto(w.getId_producto().getNombre()), w.getCantidad(), new Venta(w.getId_datos_venta().getNumerofactura()), new Cliente(w.getCliente().getNombre()), w.getTipo());
                            lista.insertar(venta);
                            combovv.clear();
                            combovv.add(String.valueOf(w.getId_detalle()));
                        }
                    }
                    Modelo_DetalleVenta ml = new Modelo_DetalleVenta(lista.toArrayAsc());
                    tabla.setModel(ml);
                    aler.exito("Busqueda", "El Dato se Encomtro con Exito..");
                }
            }
        } catch (Exception e) {
            JOptionPaneWornin a = new JOptionPaneWornin(null, true, "Busqueda", "No se pudo encontarar el registro solo 'Similares'!!!...");
            a.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void datocreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datocreditoActionPerformed
        // TODO add your handling code here:
        llenarcombo();
        String dato1 = combovv.get(filaseleccionada);
        AddDatosCreditos a = new AddDatosCreditos(null, true, null, null, String.valueOf(tabla.getValueAt(filaseleccionada, 0)), String.valueOf(tabla.getValueAt(filaseleccionada, 1)), String.valueOf(tabla.getValueAt(filaseleccionada, 3)), dato1, tipo1);
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_datocreditoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraBaja;
    private javax.swing.JTextField buscarn;
    private javax.swing.JMenuItem datocredito;
    private javax.swing.JLabel encabezado;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel salir;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField ventadd;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
