/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AppPackage.AnimationClass;
import Clases.Producto;
import Meet.Fondo;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Timer;
import Vistas.AddCargo;
import Vistas.AddCategoria;
import Vistas.AddCliente;
import Vistas.AddCompraProducto;
import Vistas.AddDetalleVenta1;
import Vistas.AddEmpleado;
import Vistas.AddProducto;
import Vistas.AddProveedor;
import Vistas.AddReferencia;
import Vistas.AddUsuario;
import Vistas.AddVenta;
import Vistas.InventarioFisico;
import Vistas.Login;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.ImageIcon;
import reportes.BOTON;

/**
 *
 * @author leo_g
 */
public class Escritorio extends javax.swing.JFrame implements Runnable {
    
    String hora, minutos, segundos, ampm;
    Calendar calendario;
    Thread h1;
    
    String tipo;
    ArrayList<Producto> pro;
    
    private Timer t;
    private ActionListener ac;
    private int x = 0;
    
    public Escritorio(String tipo1) {
        initComponents();
        fecha.setText(fecha());
        pro = new ArrayList<>();
        dessing();
        tipo = tipo1;
        h1 = new Thread(this);
        h1.start();
        this.setExtendedState(Escritorio.MAXIMIZED_BOTH);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logo.jpg")).getImage());
        if (tipo.equals("Empleado")) {
            new_usuario.setEnabled(false);
            New_empleado.setEnabled(false);
            informe.setEnabled(false);
            new_cargo.setEnabled(false);
        }
        internet.setVisible(false);
        calculadora.setVisible(false);
        musica.setVisible(false);
        facebook.setVisible(false);
        word.setVisible(false);
        youtube.setVisible(false);
//        inv.setVisible(false);
        inv.setEnabled(false);
    }
    
    public void ponerImagen(String im) {
        Fondo fondo = new Fondo(im);
        des.setBorder(fondo);
    }
    
    public final void dessing() {
        ponerImagen("pantalla.jpg");
//        jPanel2.setBackground(new Color(35, 4, 98));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        des = new javax.swing.JDesktopPane();
        ibHora = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        cliente = new javax.swing.JButton();
        empleado = new javax.swing.JButton();
        ayuda = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        productos = new javax.swing.JButton();
        vent = new javax.swing.JButton();
        informes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        new_cargo = new javax.swing.JButton();
        new_cat = new javax.swing.JButton();
        new_cliente = new javax.swing.JButton();
        com_producto = new javax.swing.JButton();
        New_empleado = new javax.swing.JButton();
        New_producto = new javax.swing.JButton();
        new_prove = new javax.swing.JButton();
        new_referencia = new javax.swing.JButton();
        new_usuario = new javax.swing.JButton();
        venta = new javax.swing.JButton();
        pago_cuotas = new javax.swing.JButton();
        inv_fisico = new javax.swing.JButton();
        inv = new javax.swing.JButton();
        informe = new javax.swing.JButton();
        acerca = new javax.swing.JButton();
        ver = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        internet = new javax.swing.JLabel();
        calculadora = new javax.swing.JLabel();
        musica = new javax.swing.JLabel();
        facebook = new javax.swing.JLabel();
        word = new javax.swing.JLabel();
        youtube = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fecha = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        des.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desMouseClicked(evt);
            }
        });

        ibHora.setBackground(new java.awt.Color(0, 0, 0));
        ibHora.setFont(new java.awt.Font("MV Boli", 1, 55)); // NOI18N
        ibHora.setForeground(new java.awt.Color(255, 255, 255));
        ibHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        des.add(ibHora);
        ibHora.setBounds(680, 270, 500, 100);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-xbox-menu-40.png"))); // NOI18N
        menu.setText("MENU");
        menu.setBorderPainted(false);
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        des.add(menu);
        menu.setBounds(-7, 0, 250, 80);

        cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cliente-de-empresa-64.png"))); // NOI18N
        cliente.setText("cliente");
        cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteMouseClicked(evt);
            }
        });
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        des.add(cliente);
        cliente.setBounds(-200, 90, 190, 90);

        empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-trabajo-permanente-64.png"))); // NOI18N
        empleado.setText("empleado");
        empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleadoMouseClicked(evt);
            }
        });
        des.add(empleado);
        empleado.setBounds(-200, 200, 190, 90);

        ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-información-64.png"))); // NOI18N
        ayuda.setText("Ayuda");
        ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ayudaMouseClicked(evt);
            }
        });
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });
        des.add(ayuda);
        ayuda.setBounds(-200, 680, 190, 80);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cierre-de-sesión-redondeado-hacia-la-izquierda-64.png"))); // NOI18N
        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        des.add(salir);
        salir.setBounds(-200, 950, 190, 80);

        productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-producto-nuevo-64.png"))); // NOI18N
        productos.setText("Productos");
        productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosMouseClicked(evt);
            }
        });
        des.add(productos);
        productos.setBounds(-200, 460, 190, 90);

        vent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-etiqueta-de-precio-64.png"))); // NOI18N
        vent.setText("Venta");
        vent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventMouseClicked(evt);
            }
        });
        vent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventActionPerformed(evt);
            }
        });
        des.add(vent);
        vent.setBounds(-200, 590, 190, 80);

        informes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-gráfico-combinado-64.png"))); // NOI18N
        informes.setText("informes");
        informes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informesMouseClicked(evt);
            }
        });
        informes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informesActionPerformed(evt);
            }
        });
        des.add(informes);
        informes.setBounds(-200, 340, 190, 80);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);
        des.add(jLabel3);
        jLabel3.setBounds(-250, 80, 240, 1000);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PANEL.png"))); // NOI18N
        jLabel1.setOpaque(true);
        des.add(jLabel1);
        jLabel1.setBounds(0, 80, 240, 1000);

        new_cargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-nuevo-empleo-40.png"))); // NOI18N
        new_cargo.setText("Nueva Cargo");
        new_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_cargoActionPerformed(evt);
            }
        });
        des.add(new_cargo);
        new_cargo.setBounds(0, 230, 160, 40);

        new_cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-derechos-de-autor-40.png"))); // NOI18N
        new_cat.setText("Nueva Categoria");
        new_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_catActionPerformed(evt);
            }
        });
        des.add(new_cat);
        new_cat.setBounds(0, 480, 180, 40);

        new_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-add-user-male-40.png"))); // NOI18N
        new_cliente.setText("Nuevo Cliente");
        new_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_clienteActionPerformed(evt);
            }
        });
        des.add(new_cliente);
        new_cliente.setBounds(0, 80, 160, 40);

        com_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-carrito-de-la-compra-cargado-40.png"))); // NOI18N
        com_producto.setText(" Compra de Producto");
        com_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_productoActionPerformed(evt);
            }
        });
        des.add(com_producto);
        com_producto.setBounds(0, 440, 180, 40);

        New_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-asistente-40.png"))); // NOI18N
        New_empleado.setText("Nuevo Empleado");
        New_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_empleadoActionPerformed(evt);
            }
        });
        des.add(New_empleado);
        New_empleado.setBounds(0, 190, 160, 40);

        New_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-nuevo-40.png"))); // NOI18N
        New_producto.setText("Nuevo Producto");
        New_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_productoActionPerformed(evt);
            }
        });
        des.add(New_producto);
        New_producto.setBounds(0, 520, 180, 40);

        new_prove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-director-de-escuela-40.png"))); // NOI18N
        new_prove.setText("Nuevo Proveedor");
        new_prove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_proveActionPerformed(evt);
            }
        });
        des.add(new_prove);
        new_prove.setBounds(0, 560, 180, 40);

        new_referencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-currículum-40.png"))); // NOI18N
        new_referencia.setText("Nueva Referencia");
        new_referencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_referenciaActionPerformed(evt);
            }
        });
        des.add(new_referencia);
        new_referencia.setBounds(0, 150, 225, 40);

        new_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-credenciales-de-usuario-40.png"))); // NOI18N
        new_usuario.setText("Nuevo Usuario");
        new_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_usuarioActionPerformed(evt);
            }
        });
        des.add(new_usuario);
        new_usuario.setBounds(0, 270, 160, 40);

        venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-venta-40.png"))); // NOI18N
        venta.setText("Venta");
        venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaActionPerformed(evt);
            }
        });
        des.add(venta);
        venta.setBounds(0, 580, 140, 50);

        pago_cuotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-efectivo-en-mano-40.png"))); // NOI18N
        pago_cuotas.setText("Pago Cuotas");
        pago_cuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pago_cuotasMouseClicked(evt);
            }
        });
        pago_cuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pago_cuotasActionPerformed(evt);
            }
        });
        des.add(pago_cuotas);
        pago_cuotas.setBounds(0, 630, 140, 49);

        inv_fisico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-mover-por-carretilla-40.png"))); // NOI18N
        inv_fisico.setText("Inventario Fisico");
        inv_fisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_fisicoActionPerformed(evt);
            }
        });
        des.add(inv_fisico);
        inv_fisico.setBounds(0, 300, 160, 50);

        inv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-lista-40.png"))); // NOI18N
        inv.setText("Inventario");
        inv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invMouseClicked(evt);
            }
        });
        des.add(inv);
        inv.setBounds(0, 350, 160, 49);

        informe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-gráfico-circular-40.png"))); // NOI18N
        informe.setText("Informes");
        informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeActionPerformed(evt);
            }
        });
        des.add(informe);
        informe.setBounds(0, 400, 160, 49);

        acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-acerca-de-40.png"))); // NOI18N
        acerca.setText("Acerca de...");
        acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaActionPerformed(evt);
            }
        });
        des.add(acerca);
        acerca.setBounds(0, 740, 140, 49);

        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-preguntas-40.png"))); // NOI18N
        ver.setText("Ver Ayuda");
        ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMouseClicked(evt);
            }
        });
        des.add(ver);
        ver.setBounds(0, 680, 140, 50);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Menu_32px.png"))); // NOI18N
        jButton15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Menu_32px_1.png"))); // NOI18N
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Menu_32px_1.png"))); // NOI18N
        jButton15.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Menu_32px_1.png"))); // NOI18N
        jButton15.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Menu_32px_1.png"))); // NOI18N
        jButton15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton15MouseMoved(evt);
            }
        });
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton15MouseExited(evt);
            }
        });
        des.add(jButton15);
        jButton15.setBounds(1850, 10, 65, 41);

        internet.setBackground(new java.awt.Color(255, 255, 0));
        internet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Globe_32px.png"))); // NOI18N
        internet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        internet.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                internetMouseMoved(evt);
            }
        });
        internet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                internetMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                internetMouseExited(evt);
            }
        });
        des.add(internet);
        internet.setBounds(1870, 60, 34, 34);

        calculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Calculator_32px.png"))); // NOI18N
        calculadora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        calculadora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                calculadoraMouseMoved(evt);
            }
        });
        calculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculadoraMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calculadoraMouseExited(evt);
            }
        });
        des.add(calculadora);
        calculadora.setBounds(1870, 90, 34, 34);

        musica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Musical_Notes_32px.png"))); // NOI18N
        musica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        musica.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                musicaMouseMoved(evt);
            }
        });
        musica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musicaMouseExited(evt);
            }
        });
        des.add(musica);
        musica.setBounds(1870, 120, 34, 34);

        facebook.setForeground(new java.awt.Color(255, 255, 255));
        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/facebook_on.png"))); // NOI18N
        facebook.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                facebookMouseMoved(evt);
            }
        });
        facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facebookMouseExited(evt);
            }
        });
        des.add(facebook);
        facebook.setBounds(1870, 160, 32, 32);

        word.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/word_on.png"))); // NOI18N
        word.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        word.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                wordMouseMoved(evt);
            }
        });
        word.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wordMouseExited(evt);
            }
        });
        des.add(word);
        word.setBounds(1870, 200, 34, 34);

        youtube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/youtube_on.png"))); // NOI18N
        youtube.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        youtube.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                youtubeMouseMoved(evt);
            }
        });
        youtube.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                youtubeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                youtubeMouseExited(evt);
            }
        });
        des.add(youtube);
        youtube.setBounds(1870, 240, 34, 34);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.jpg"))); // NOI18N
        des.add(jLabel2);
        jLabel2.setBounds(1710, 880, 210, 200);
        des.add(jSeparator1);
        jSeparator1.setBounds(630, 380, 600, 40);

        fecha.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        des.add(fecha);
        fecha.setBounds(690, 400, 480, 50);

        cerrar.setText("Cerrar Sesion");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        des.add(cerrar);
        cerrar.setBounds(0, 910, 170, 40);

        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        des.add(exit);
        exit.setBounds(0, 1020, 170, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(des, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(des, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_cargoActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        
        AddCargo c = new AddCargo(this, true, tipo);
        c.setVisible(true);

    }//GEN-LAST:event_new_cargoActionPerformed

    private void new_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_catActionPerformed
        
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        
        AddCategoria c = new AddCategoria(this, true, tipo);
        c.setVisible(true);
    }//GEN-LAST:event_new_catActionPerformed

    private void new_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_clienteActionPerformed
        
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        
        AddCliente c = new AddCliente(this, true, tipo);
        c.setVisible(true);
    }//GEN-LAST:event_new_clienteActionPerformed

    private void com_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_productoActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        
        AddCompraProducto p = new AddCompraProducto(this, true, null, null, tipo);
        p.setVisible(true);
    }//GEN-LAST:event_com_productoActionPerformed

    private void New_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_empleadoActionPerformed
        
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        AddEmpleado e = new AddEmpleado(this, true, tipo);
        e.setVisible(true);
    }//GEN-LAST:event_New_empleadoActionPerformed

    private void New_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_productoActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        AddProducto p = new AddProducto(this, true, tipo);
        p.setVisible(true);
    }//GEN-LAST:event_New_productoActionPerformed

    private void new_proveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_proveActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        AddProveedor p = new AddProveedor(this, true, tipo);
        p.setVisible(true);
    }//GEN-LAST:event_new_proveActionPerformed

    private void new_referenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_referenciaActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        AddReferencia r = new AddReferencia(this, true, null, null, tipo);
        r.setVisible(true);
    }//GEN-LAST:event_new_referenciaActionPerformed

    private void new_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_usuarioActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        AddUsuario u = new AddUsuario(this, true, tipo);
        u.setVisible(true);
    }//GEN-LAST:event_new_usuarioActionPerformed

    private void ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        
        AddVenta v = new AddVenta(this, true, null, null, null, "", tipo);
        v.setVisible(true);
    }//GEN-LAST:event_ventaActionPerformed

    private void pago_cuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pago_cuotasActionPerformed
        // TODO add your handling code here:
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        
        AddDetalleVenta1 x = new AddDetalleVenta1(null, true, null, null, null, "", "", tipo, 0);
        x.setVisible(true);

    }//GEN-LAST:event_pago_cuotasActionPerformed

    private void inv_fisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_fisicoActionPerformed
        // TODO add your handling code here:
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        
        InventarioFisico f = new InventarioFisico(this, true, tipo);
        f.setVisible(true);
    }//GEN-LAST:event_inv_fisicoActionPerformed

    private void informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        
        BOTON f = new BOTON();
        f.setVisible(true);
    }//GEN-LAST:event_informeActionPerformed

    private void ventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
//        AddVenta v = new AddVenta(this, true, null, null, null, "", tipo);
//        v.setVisible(true);

    }//GEN-LAST:event_ventActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void informesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_informesActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        

    }//GEN-LAST:event_salirActionPerformed

    private void acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, acerca);
        a.jButtonXLeft(250, 0, 10, 5, ver);
        acercade v = new acercade();
        v.setVisible(true);
    }//GEN-LAST:event_acercaActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaActionPerformed

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        AnimationClass a = new AnimationClass();
// sacar botones principales
        a.jLabelXRight(-250, 0, 5, 5, jLabel3);
        a.jButtonXRight(-200, 30, 5, 5, cliente);
        a.jButtonXRight(-200, 30, 10, 5, empleado);
        a.jButtonXRight(-200, 30, 10, 5, productos);
        a.jButtonXRight(-200, 30, 10, 5, informes);
        a.jButtonXRight(-200, 30, 10, 5, vent);
        a.jButtonXRight(-200, 30, 10, 5, ayuda);
        a.jButtonXRight(-200, 30, 10, 5, salir);
// meter botones principales 
        a.jLabelXLeft(0, -250, 10, 5, jLabel3);
        a.jButtonXLeft(30, -200, 10, 5, cliente);
        a.jButtonXLeft(30, -200, 10, 5, empleado);
        a.jButtonXLeft(30, -200, 10, 5, productos);
        a.jButtonXLeft(30, -200, 10, 5, vent);
        a.jButtonXLeft(30, -200, 10, 5, informes);
        a.jButtonXLeft(30, -200, 10, 5, ayuda);
        a.jButtonXLeft(30, -200, 10, 5, salir);

// meter secundarios
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        a.jButtonXLeft(250, 0, 10, 5, ver);
        a.jButtonXLeft(250, 0, 10, 5, acerca);
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jLabelXLeft(0, -200, 10, 5, jLabel3);

    }//GEN-LAST:event_menuMouseClicked

    private void jButton15MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15MouseMoved

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        internet.setVisible(true);
        calculadora.setVisible(true);
        musica.setVisible(true);
        facebook.setVisible(true);
        word.setVisible(true);
        youtube.setVisible(true);
        ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                x = x + 1;
                if (x == 100) {
                    internet.setVisible(false);
                    calculadora.setVisible(false);
                    musica.setVisible(false);
                    facebook.setVisible(false);
                    word.setVisible(false);
                    youtube.setVisible(false);
                    t.stop();
                    x = 1;
                }
            }
        };
        t = new Timer(50, ac);
        t.start();
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15MouseExited

    private void internetMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internetMouseMoved
        // TODO add your handling code here:
        internet.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_internetMouseMoved

    private void internetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internetMouseClicked
        // TODO add your handling code here:
        Openinterner();
    }//GEN-LAST:event_internetMouseClicked

    private void internetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internetMouseExited
        internet.setBackground(new Color(255, 255, 255, 0));
        internet.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_internetMouseExited

    private void calculadoraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculadoraMouseMoved
        // TODO add your handling code here:
        calculadora.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
        calculadora.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_calculadoraMouseMoved

    private void calculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculadoraMouseClicked
        // TODO add your handling code here:
        try {
            Runtime run = Runtime.getRuntime();
            Process p = run.exec("calc");
            p.waitFor();
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_calculadoraMouseClicked

    private void calculadoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculadoraMouseExited
        // TODO add your handling code here:
        calculadora.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_calculadoraMouseExited

    private void musicaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicaMouseMoved
        // TODO add your handling code here:
        musica.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
        musica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_musicaMouseMoved

    private void musicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicaMouseClicked
        // TODO add your handling code here:
        Openmisic();
    }//GEN-LAST:event_musicaMouseClicked

    private void musicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicaMouseExited
        // TODO add your handling code here:
        musica.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_musicaMouseExited

    private void facebookMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseMoved
        // TODO add your handling code here:
        facebook.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GREEN));
        facebook.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_facebookMouseMoved

    private void facebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseClicked
        // TODO add your handling code here:
        Openfecebook();
    }//GEN-LAST:event_facebookMouseClicked

    private void facebookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseExited
        // TODO add your handling code here:
        facebook.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_facebookMouseExited

    private void wordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordMouseMoved
        // TODO add your handling code here:
        word.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GREEN));
        word.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_wordMouseMoved

    private void wordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordMouseClicked
        // TODO add your handling code here:
        OpenWord();
    }//GEN-LAST:event_wordMouseClicked

    private void wordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordMouseExited
        // TODO add your handling code here:
        word.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_wordMouseExited

    private void youtubeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_youtubeMouseMoved
        // TODO add your handling code here:
        youtube.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GREEN));
        youtube.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_youtubeMouseMoved

    private void youtubeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_youtubeMouseClicked
        // TODO add your handling code here:
        Openyoutube();
    }//GEN-LAST:event_youtubeMouseClicked

    private void youtubeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_youtubeMouseExited
        // TODO add your handling code here:
        youtube.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_youtubeMouseExited

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void desMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desMouseClicked
        AnimationClass a = new AnimationClass();
        a.jLabelXLeft(0, -250, 10, 5, jLabel3);
        a.jButtonXLeft(30, -200, 10, 5, cliente);
        a.jButtonXLeft(30, -200, 10, 5, empleado);
        a.jButtonXLeft(30, -200, 10, 5, productos);
        a.jButtonXLeft(30, -200, 10, 5, vent);
        a.jButtonXLeft(30, -200, 10, 5, informes);
        a.jButtonXLeft(30, -200, 10, 5, ayuda);
        a.jButtonXLeft(30, -200, 10, 5, salir);
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        a.jButtonXLeft(250, 0, 10, 5, ver);
        a.jButtonXLeft(250, 0, 10, 5, acerca);
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);
    }//GEN-LAST:event_desMouseClicked

    private void clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseClicked
        AnimationClass a = new AnimationClass();
        
        a.jButtonXRight(0, 250, 10, 5, new_cliente);
        a.jButtonXRight(0, 250, 10, 5, new_referencia);
        
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        a.jButtonXLeft(250, 0, 10, 5, ver);
        a.jButtonXLeft(250, 0, 10, 5, acerca);
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);

    }//GEN-LAST:event_clienteMouseClicked

    private void empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadoMouseClicked
        AnimationClass a = new AnimationClass();
        a.jButtonXRight(0, 250, 10, 5, New_empleado);
        a.jButtonXRight(0, 250, 10, 5, new_usuario);
        a.jButtonXRight(0, 250, 10, 5, new_cargo);
        
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        a.jButtonXLeft(250, 0, 10, 5, ver);
        a.jButtonXLeft(250, 0, 10, 5, acerca);
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);
    }//GEN-LAST:event_empleadoMouseClicked

    private void ayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaMouseClicked
        AnimationClass a = new AnimationClass();
        a.jButtonXRight(0, 250, 10, 5, ver);
        a.jButtonXRight(0, 250, 10, 5, acerca);
        
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        a.jButtonXLeft(250, 0, 10, 5, ver);
        a.jButtonXLeft(250, 0, 10, 5, acerca);
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);
    }//GEN-LAST:event_ayudaMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        AnimationClass a = new AnimationClass();
        
        a.jButtonXRight(0, 250, 10, 5, exit);
        a.jButtonXRight(0, 250, 10, 5, cerrar);
        
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        a.jButtonXLeft(250, 0, 10, 5, ver);
        a.jButtonXLeft(250, 0, 10, 5, acerca);
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);
    }//GEN-LAST:event_salirMouseClicked

    private void productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosMouseClicked
        AnimationClass a = new AnimationClass();
        
        a.jButtonXRight(0, 250, 10, 5, New_producto);
        a.jButtonXRight(0, 250, 10, 5, com_producto);
        a.jButtonXRight(0, 250, 10, 5, new_prove);
        a.jButtonXRight(0, 250, 10, 5, new_cat);
        
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        a.jButtonXLeft(250, 0, 10, 5, ver);
        a.jButtonXLeft(250, 0, 10, 5, acerca);
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);
    }//GEN-LAST:event_productosMouseClicked

    private void ventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventMouseClicked
        
        AnimationClass a = new AnimationClass();
        
        a.jButtonXRight(0, 250, 10, 5, venta);
        a.jButtonXRight(0, 250, 10, 5, pago_cuotas);
        
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        a.jButtonXLeft(250, 0, 10, 5, ver);
        a.jButtonXLeft(250, 0, 10, 5, acerca);
        a.jButtonXLeft(250, 0, 10, 5, new_prove);
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);

    }//GEN-LAST:event_ventMouseClicked

    private void informesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informesMouseClicked
        AnimationClass a = new AnimationClass();
        
        a.jButtonXRight(0, 250, 10, 5, inv_fisico);
        a.jButtonXRight(0, 250, 10, 5, inv);
        a.jButtonXRight(0, 250, 10, 5, informe);
        
        a.jButtonXLeft(250, 0, 10, 5, new_cliente);
        a.jButtonXLeft(250, 0, 10, 5, new_referencia);
        a.jButtonXLeft(250, 0, 10, 5, New_producto);
        a.jButtonXLeft(250, 0, 10, 5, New_empleado);
        a.jButtonXLeft(250, 0, 10, 5, com_producto);
        a.jButtonXLeft(250, 0, 10, 5, informe);
        a.jButtonXLeft(250, 0, 10, 5, inv);
        a.jButtonXLeft(250, 0, 10, 5, inv_fisico);
        a.jButtonXLeft(250, 0, 10, 5, new_cargo);
        a.jButtonXLeft(250, 0, 10, 5, new_cat);
        a.jButtonXLeft(250, 0, 10, 5, new_usuario);
        a.jButtonXLeft(250, 0, 10, 5, pago_cuotas);
        a.jButtonXLeft(250, 0, 10, 5, venta);
        a.jButtonXLeft(250, 0, 10, 5, ver);
        a.jButtonXLeft(250, 0, 10, 5, acerca);
        a.jButtonXLeft(250, 0, 10, 5, new_prove);

    }//GEN-LAST:event_informesMouseClicked

    private void pago_cuotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pago_cuotasMouseClicked
        

    }//GEN-LAST:event_pago_cuotasMouseClicked

    private void verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseClicked
        try {
            File path = new File("Manual ESD.pdf");
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_verMouseClicked

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        
        AnimationClass a = new AnimationClass();
        a.jButtonXLeft(250, 0, 10, 5, exit);
        a.jButtonXLeft(250, 0, 10, 5, cerrar);
        
        Login v = new Login();
        this.dispose();
        v.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

//GEN-FIRST:event_invMouseClicked
 
//GEN-LAST:event_invMouseClicked

   public void Openinterner() {
        try {
            Desktop.getDesktop().browse(URI.create("www.google.com"));
        } catch (Exception e) {
            
        }
    }
    
    public void Openfecebook() {
        try {
            Desktop.getDesktop().browse(URI.create("www.facebook.com"));
        } catch (Exception e) {
            
        }
    }
    
    public void Openyoutube() {
        try {
            Desktop.getDesktop().browse(URI.create("www.youtube.com"));
        } catch (Exception e) {
            
        }
    }
    
    public void OpenWord() {
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE");
            p.waitFor();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } catch (InterruptedException ie) {
            ie.printStackTrace();
        }
    }
    
    public void Openmisic() {
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("C:\\Program Files\\Windows Media Player\\wmplayer.exe");
            p.waitFor();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } catch (InterruptedException ie) {
            ie.printStackTrace();
        }
    }
    
    public void calcula() {
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();
        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";
        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }
    
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            calcula();
            ibHora.setText(hora + ":" + minutos + ":" + segundos + " " + ampm);
            
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static String fecha() {
        
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        return formato.format(fecha);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton New_empleado;
    private javax.swing.JButton New_producto;
    private javax.swing.JButton acerca;
    private javax.swing.JButton ayuda;
    private javax.swing.JLabel calculadora;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton cliente;
    private javax.swing.JButton com_producto;
    private javax.swing.JDesktopPane des;
    private javax.swing.JButton empleado;
    private javax.swing.JButton exit;
    private javax.swing.JLabel facebook;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel ibHora;
    private javax.swing.JButton informe;
    private javax.swing.JButton informes;
    private javax.swing.JLabel internet;
    private javax.swing.JButton inv;
    private javax.swing.JButton inv_fisico;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton menu;
    private javax.swing.JLabel musica;
    private javax.swing.JButton new_cargo;
    private javax.swing.JButton new_cat;
    private javax.swing.JButton new_cliente;
    private javax.swing.JButton new_prove;
    private javax.swing.JButton new_referencia;
    private javax.swing.JButton new_usuario;
    private javax.swing.JButton pago_cuotas;
    private javax.swing.JButton productos;
    private javax.swing.JButton salir;
    private javax.swing.JButton vent;
    private javax.swing.JButton venta;
    private javax.swing.JButton ver;
    private javax.swing.JLabel word;
    private javax.swing.JLabel youtube;
    // End of variables declaration//GEN-END:variables

}
