/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.io.*;
import Clases.CompraProducto;
import Clases.Detalle_venta;
import Clases.Producto;
import Clases.Venta;
import Clases.inventario;
import Dao.Dao_CompraProducto;
import Dao.Dao_Detalle_venta;
import Estructuras.ColaNodo;
import Modelos.Modelo_Inventario;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Frame;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author leo_g
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    ArrayList<inventario> refere;
    ArrayList<inventario> a;
    CompraProducto compra;
    CompraProducto compraproducto;
    Detalle_venta detalleV;
    ColaNodo cola;
    String tipo1;
    Dao_CompraProducto com;
    Dao_Detalle_venta detalle;
    
    ArrayList<Producto> combo;

    public Inventario(java.awt.Frame parent, boolean modal, ArrayList<Producto> combo1, String tipo2) {
        // super(parent, modal);
        initComponents();
        tipo1 = tipo2;
        compra = new CompraProducto();
        cola = new ColaNodo();
        a = new ArrayList();
        combo = combo1;
        com = new Dao_CompraProducto();
        detalle = new Dao_Detalle_venta();
        detalleV = new Detalle_venta();
        compraproducto = new CompraProducto();
        if (combo != null) {
            for (Producto e : combo) {
                producto.setText(e.getNombre());
            }
        }
        this.setLocationRelativeTo(null);
        // llenartabla();
    }

    public void llenarCola() {
        cola = new ColaNodo();
        for (CompraProducto w : com.listaCompraProducto()) {
          //  compraproducto = new CompraProducto(w.getIdcompra(), w.getCantidad(), w.getPrecio(), w.getFechaadquisiscion(), new Producto(w.getProducto().getNombre()));
            cola.offer(compraproducto);
        }
    }
////     public void SacarCola() {
////                for (Detalle_venta w : detalle.listaDetalle_venta()) {
////            detalleV = new Detalle_venta(w.getIdcompra(), w.getCantidad(), w.getPrecio(), w.getFechaadquisiscion(), new Producto(w.getProducto().getNombre()));
////            cola.offer(compraproducto);
////        }
////    }

    public void llenartabla() {
//       Modelo_Inventario ml = new Modelo_Inventario(cola.mostrar());
//      jTable1.setModel(ml);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        producto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Control de inventario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1290, 47));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Producto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        producto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 138, 32), 1, true));
        producto.setEnabled(false);
        getContentPane().add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 209, 37));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "KARDEX", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Movimiento", "Cantidad", "Costo/U", "Costo Total", "Cantidad", "Costo/U", "Costo Total", "Cantidad", "Costo/U", "Costo Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("SALIDA");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 138, 32), 1, true));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("EXISTENCIA");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 138, 32), 1, true));

        jLabel15.setBackground(new java.awt.Color(204, 255, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ENTRADA");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 138, 32), 1, true));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1244, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-window-20 (1).png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-window-20.png"))); // NOI18N
        jButton7.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-window-20.png"))); // NOI18N
        jButton7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-close-window-20.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 30, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setOpaque(true);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        jSeparator1.setBackground(new java.awt.Color(236, 138, 32));
        jSeparator1.setForeground(new java.awt.Color(236, 138, 32));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 72, 280, 10));

        jPanel1.setBackground(new java.awt.Color(236, 138, 32));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial-medico.png"))); // NOI18N
        jButton2.setText("Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1181, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1290, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (producto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione el producto");
        } else if (isEmpty(jTable1) == false) {
            JOptionPane.showMessageDialog(null, "El producto no posee ningun registro");
        } else {
            try {
                Document documento = new Document(PageSize.A4.rotate()) {
                };
                PdfWriter.getInstance((com.itextpdf.text.Document) documento, new FileOutputStream("Nombre del producto" + ".pdf"));
                documento.open();

                Font textoFont = FontFactory.getFont(FontFactory.TIMES, 16f, Font.BOLD);
                Font subTextFont = FontFactory.getFont(FontFactory.TIMES, 14f, Font.BOLD);
                Font pequeño = FontFactory.getFont(FontFactory.TIMES, 12f, Font.NORMAL);

                Paragraph texto = new Paragraph("Control de Inventario (PEPS)", textoFont);
                texto.setAlignment(Element.ALIGN_CENTER);
                Paragraph subText = new Paragraph("Kardex", pequeño);
                subText.setAlignment(Element.ALIGN_CENTER);

                Phrase tituloCentro = new Phrase("Producto: " + producto.getText(), textoFont);
                Phrase subTituloCentro = new Phrase("Cantidad Dispinible: ", subTextFont);

                documento.add(texto);
                documento.add(subText);

                documento.add(new Paragraph(" "));
                documento.add(tituloCentro);
                documento.add(new Paragraph(" "));
                documento.add(subTituloCentro);
                documento.add(new Paragraph(" "));

                PdfPTable tabla = new PdfPTable(11);

                Font titulo = FontFactory.getFont(FontFactory.TIMES, 10f, Font.BOLD);
                Font informacion = FontFactory.getFont(FontFactory.TIMES, 10f);

                PdfPCell union = new PdfPCell(new Phrase(" ", titulo));
                union.setColspan(2);
                tabla.addCell(union);
                PdfPCell union2 = new PdfPCell(new Phrase("Entrada ", titulo));
                union2.setHorizontalAlignment(Element.ALIGN_CENTER);
                union2.setColspan(3);
                tabla.addCell(union2);
                PdfPCell union3 = new PdfPCell(new Phrase("Salida ", titulo));
                union3.setHorizontalAlignment(Element.ALIGN_CENTER);
                union3.setColspan(3);
                tabla.addCell(union3);
                PdfPCell union4 = new PdfPCell(new Phrase("Saldo", titulo));
                union4.setHorizontalAlignment(Element.ALIGN_CENTER);
                union4.setColspan(3);
                tabla.addCell(union4);

                PdfPCell c1 = new PdfPCell(new Phrase("Fecha", titulo));
                c1.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(c1);
                PdfPCell c2 = new PdfPCell(new Phrase("Movimiento", titulo));
                c2.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(c2);
                for (int i = 0; i < 3; i++) {
                    PdfPCell c3 = new PdfPCell(new Phrase("Cantidad", titulo));
                    c3.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tabla.addCell(c3);
                    PdfPCell c4 = new PdfPCell(new Phrase("Precio($)", titulo));
                    c4.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tabla.addCell(c4);
                    PdfPCell c5 = new PdfPCell(new Phrase("Total($)", titulo));
                    c5.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tabla.addCell(c5);
                }

                int filas = jTable1.getRowCount();
                int columnas = jTable1.getColumnCount();

                String valor = null;
                for (int i = 0; i < filas; i++) {

                    for (int j = 0; j < columnas; j++) {

                        if (jTable1.getValueAt(i, j).toString() != null) {
                            valor = jTable1.getValueAt(i, j).toString();
                        } else {
                            valor = " ";
                        }
                        PdfPCell info = new PdfPCell(new Phrase(valor, informacion));

                        info.setHorizontalAlignment(Element.ALIGN_CENTER);
                        tabla.addCell(info);
                    }
                }

                tabla.completeRow();
                float tam[] = {30f, 40f, 30f, 30f, 30f, 30f, 30f, 30f, 30f, 30f, 30f};
                tabla.setWidths(tam);

                documento.add(tabla);
                documento.add(new Paragraph(" "));
                documento.add(new Paragraph("UES-FMP-ESD  " + darFormato(new Date())));
                documento.close();

                abrirArchivo("Nombre del producto" + ".pdf");

            } catch (DocumentException | FileNotFoundException e) {
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        refere.add(new inventario(new Producto(producto.getText())));
//
        viewProductoinven cli = new viewProductoinven(null, true, tipo1);
        this.dispose();
        cli.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    public static String darFormato(Date date) {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("ddMMMyyyy hh:mm");
        return simpleDateFormat.format(date).toUpperCase();
    }

    public void abrirArchivo(String archivo) {

        try {
            File objetofile = new File(archivo);
            Desktop.getDesktop().open(objetofile);
        } catch (IOException e) {
        }

    }

    public static boolean isEmpty(JTable jTable) {
        if (jTable != null && jTable.getModel() != null) {
            return jTable.getModel().getRowCount() <= 0 ? true : false;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField producto;
    // End of variables declaration//GEN-END:variables
}
